baseURL = "https://gophersource.com"
languageCode = "en-us"
title = "GopherSource"
theme = "gopher"

[params]
  description = "An open-source adventure for gophers"
  image = "https://twiter-card--gophersource.netlify.com/img/gopher-balloons.twitter.png"
